"""
★ PHASE 4 — Artifact Agent

Generates a compact, shareable Trip Brief in Markdown format.
This is the "output artifact" of the entire multi-agent pipeline.

The brief includes:
  - Destination summary, dates, traveller count
  - Full cost breakdown
  - Weather summary
  - Top 5 highlights
  - Packing essentials (compact)
  - Emergency contacts + useful phrases
  - Quick tips from the Architect Agent

The frontend offers this as a downloadable .md file.
"""
from __future__ import annotations
from app.services.llm_service import call_llm, is_llm_available


def run(trip_result: dict) -> str:
    """
    Returns a Markdown string (the Trip Brief).
    Falls back to a template-generated brief if LLM unavailable.
    """
    dest        = trip_result.get("destination", "Unknown")
    meta        = trip_result.get("meta", {})
    cost        = trip_result.get("cost", 0)
    travel      = trip_result.get("travel", "")
    hotel       = trip_result.get("hotel", "")
    weather     = trip_result.get("weather", [])
    packing     = trip_result.get("packing", [])
    itinerary   = trip_result.get("itinerary", [])
    architect   = trip_result.get("architect", {})
    breakdown   = trip_result.get("budget_breakdown", {})
    start_date  = meta.get("start_date", "")
    end_date    = meta.get("end_date", "")
    days        = meta.get("days", 0)
    from_city   = meta.get("from_city", "")
    prefs       = meta.get("preferences", [])

    # ── Weather summary line ──
    weather_summary = ""
    if weather:
        avg_max = round(sum(d.get("temp_max", 28) for d in weather) / len(weather))
        avg_min = round(sum(d.get("temp_min", 18) for d in weather) / len(weather))
        cond    = weather[0].get("condition", "")
        weather_summary = f"{avg_min}°C – {avg_max}°C, {cond}"

    # ── Packing summary (first 3 categories, 3 items each) ──
    packing_lines = []
    for cat in packing[:3]:
        items = ", ".join(cat.get("items", [])[:3])
        packing_lines.append(f"- **{cat.get('category','')}**: {items}")
    packing_md = "\n".join(packing_lines) if packing_lines else "- Pack light, layer up"

    # ── Itinerary highlights (day titles only) ──
    itin_lines = "\n".join(
        [f"- **Day {d['day']}**: {d['title']}" for d in itinerary[:days]]
    ) or "- Explore local highlights each day"

    # ── Try LLM for the tips section ──
    tips_md = ""
    if is_llm_available():
        prompt = (
            f"You are a travel writer. Write 3 punchy, practical insider tips "
            f"for a {days}-day trip to {dest} in India, "
            f"for someone who likes {', '.join(prefs) if prefs else 'general travel'}. "
            f"Keep each tip under 20 words. Use plain bullet points starting with '-'."
        )
        raw = call_llm(prompt)
        if raw and not raw.startswith("__LLM"):
            tips_md = raw.strip()

    if not tips_md:
        tips_md = (
            f"- Book transport early for the {start_date} to {end_date} peak period\n"
            f"- Keep digital copies of all tickets and IDs\n"
            f"- Download offline maps for {dest} before you leave"
        )

    # ── Assemble the brief ──
    brief = f"""# ✈️ Trip Brief — {dest}
*Generated by TripAI Mission Control*

---

## 📋 Trip Overview
| | |
|---|---|
| **From** | {from_city} |
| **Destination** | {dest} |
| **Dates** | {start_date} → {end_date} ({days} days) |
| **Transport** | {travel} |
| **Stay** | {hotel} |
| **Total Cost** | ₹{cost:,} |

---

## 💰 Budget Breakdown
| Category | Amount |
|---|---|
| Travel (return) | ₹{breakdown.get('travel', 0):,} |
| Hotel | ₹{breakdown.get('hotel', 0):,} |
| Food | ₹{breakdown.get('food', 0):,} |
| Activities | ₹{breakdown.get('activities', 0):,} |
| **Total** | **₹{cost:,}** |

---

## 🌤️ Weather
{weather_summary or 'Check local forecast before departure'}

---

## 🗺️ Trip Structure
{f"**Base Area**: {architect.get('base_area', dest)}" if architect else f"**Base**: {dest}"}
{f"**Pacing**: {architect.get('pacing', '')}" if architect else ""}
{f"**Must-dos**: {architect.get('must_dos', '')}" if architect else ""}
{f"> ⚠️ {architect.get('avoid_notes', '')}" if architect.get('avoid_notes') else ""}

---

## 📅 Day-by-Day Overview
{itin_lines}

---

## 🎒 Packing Essentials
{packing_md}

---

## 💡 Insider Tips
{tips_md}

---

## 🚨 Emergency Contacts (India)
| Service | Number |
|---|---|
| Police | 100 |
| Ambulance | 108 |
| Tourist Helpline | 1800-111-363 |
| Railway Enquiry | 139 |

---

*TripAI v2.0 — Phases 1-4 complete | Powered by Ollama llama3 + Open-Meteo*
"""
    return brief.strip()
