from __future__ import annotations

import json
import threading

from fastapi import APIRouter
from fastapi.responses import JSONResponse, StreamingResponse

from app.models.schemas import TripRequest
from app.services import mission_control
from app.services.trip_store import trip_store
from app.services.llm_service import is_llm_available

router = APIRouter()


@router.get("/health")
async def health():
    return {
        "status":        "ok",
        "llm_available": is_llm_available(),
        "version":       "4.0.0",
    }


# ── Phase 4: non-blocking dispatch ────────────────────────────────────────

@router.post("/negotiate")
async def negotiate(req: TripRequest):
    """
    Immediately reserves a trip_id and fires the Mission Control
    pipeline in a background thread. Returns the trip_id so the
    client can open the SSE stream straight away.
    """
    data     = req.model_dump()
    trip_id  = trip_store.reserve()
    q        = mission_control.get_or_create_queue(trip_id)

    thread = threading.Thread(
        target=mission_control.dispatch,
        args=(data, trip_id),
        daemon=True,
    )
    thread.start()

    return {"trip_id": trip_id, "status": "dispatched"}


# ── SSE stream ────────────────────────────────────────────────────────────

@router.get("/negotiate/stream/{trip_id}")
async def negotiate_stream(trip_id: str):
    """
    Server-Sent Events endpoint.  The client receives one JSON object
    per agent event until the sentinel None is received.
    """
    q = mission_control.get_or_create_queue(trip_id)

    def event_generator():
        while True:
            event = q.get()
            if event is None:
                mission_control.cleanup_queue(trip_id)
                yield "event: done\ndata: {}\n\n"
                break
            yield f"data: {json.dumps(event)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control":               "no-cache",
            "X-Accel-Buffering":           "no",
            "Access-Control-Allow-Origin": "*",
        },
    )


# ── Trip retrieval ────────────────────────────────────────────────────────

@router.get("/trip/{trip_id}")
async def get_trip(trip_id: str):
    trip = trip_store.get(trip_id)
    if not trip:
        return JSONResponse(status_code=404, content={"detail": "Trip not found"})
    return trip


@router.get("/trip/{trip_id}/brief")
async def get_brief(trip_id: str):
    """Returns the Trip Brief markdown generated by ArtifactAgent."""
    trip = trip_store.get(trip_id)
    if not trip:
        return JSONResponse(status_code=404, content={"detail": "Trip not found"})
    brief = trip.get("trip_brief", "")
    if not brief:
        return JSONResponse(status_code=404, content={"detail": "Brief not yet generated"})
    return {"trip_id": trip_id, "brief": brief}


@router.get("/trips")
async def list_trips():
    trips = trip_store.list_recent(20)
    return {"trips": trips, "total": trip_store.count()}
